### ISSUE TITLE
使用22日最新的库运行出现错误

### ISSUE THREAD

**Issue by hhhkkk520** [0honus0/1024-Autoreply#40]
在本地运行，这次更改以前都是正常的
显示
````
检测到 1 个账号
````
后卡住不动，取消运行后显示
````
Traceback (most recent call last):
  File "/www/1024-Autoreply-Multi_User/1024.py", line 321, in <module>
    au=auto.login1()
  File "/www/1024-Autoreply-Multi_User/1024.py", line 50, in login1
    login=self.s.post(self.loginurl,headers=self.headers,data=data)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
````

**Comment by 0honus0** [comment]
今晚有一位老哥也这样，但我本地测试正常之后他也正常了，所以不清楚原因，可以看下有没有image开头的文件之类删除之后重试

**Comment by hhhkkk520** [comment]
好的，文件夹内已经删得只剩 1024 config 和getver1了，错误还是复现
但既然原因未知，我还是换一台机器试试吧

**Comment by 0honus0** [comment]
恩，还是不行的话，提供下账号密码我晚上测试一下

**Comment by hhhkkk520** [comment]
换了一台机器正常了，谢谢
问题我就关闭了
