### ISSUE TITLE
actions运行失败

### ISSUE THREAD

**Issue by onlyJinx** [0honus0/1024-Autoreply#43]
添加了账号，密码，验证器生成码，运行时报错了，请帮忙看下

``` 
shell: /usr/bin/bash -e {0}
  env:
    USER: ***
    PASSWORD: ***
    SECRET: ***
    TOKER: 
    CODEUSER: 
    CODEPASS: 
检测到 1 个账号
Traceback (most recent call last):
  File "1024.py", line 33[5](https://github.com/onlyJinx/1024-Autoreply/runs/5596545723?check_suite_focus=true#step:5:5), in <module>
    if auto.login2()=='已經順利登錄':
  File "1024.py", line [6](https://github.com/onlyJinx/1024-Autoreply/runs/5596545723?check_suite_focus=true#step:5:6)4, in login2
    my_token = otp.get_totp(self.secret)
  File "/home/runner/.local/lib/python3.[8](https://github.com/onlyJinx/1024-Autoreply/runs/5596545723?check_suite_focus=true#step:5:8)/site-packages/onetimepass/__init__.py", line 164, in get_totp
    return get_hotp(
  File "/home/runner/.local/lib/python3.8/site-packages/onetimepass/__init__.py", line [11](https://github.com/onlyJinx/1024-Autoreply/runs/5596545723?check_suite_focus=true#step:5:11)3, in get_hotp
    key = base64.b32decode(secret, casefold=casefold)
  File "/usr/lib/python3.8/base64.py", line [20](https://github.com/onlyJinx/1024-Autoreply/runs/5596545723?check_suite_focus=true#step:5:20)5, in b32decode
    raise binascii.Error('Incorrect padding')
binascii.Error: Incorrect padding
Error: Process completed with exit code 1.
```

**Comment by 0honus0** [comment]
密钥格式有问题或有空格，获取二次验证码失败

**Comment by onlyJinx** [comment]
我充值了一下password，格式为数字字母，user是纯英文，SECRET我填的是验证器生成的六位数字，我反复检查没有空格，还有其他原因嘛？

**Comment by 0honus0** [comment]
不是六位数，是二次验证的密钥

**Comment by onlyJinx** [comment]
可以了，多谢~
顺便问下，使用action的方式运行时能否看到python的print内容。。。

**Comment by 0honus0** [comment]
运行完可以

**Comment by onlyJinx** [comment]
嗯，多谢啦
